language: objective-c
cache: cocoapods 
podfile: QCloudCOSXMLDemo/Podfile 
XCODE_WORKSPACE: QCloudCOSXMLDemo/QCloudCOSXMLDemo.xcworkspace
SCHEME: QCloudCOSXMLDemo/QCloudCOSXMLDemoTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
script: xcodebuild build-for-testing   -workspace"$XCODE_WORKSPACE" -scheme  "$SCHEME  -allowProvisioningUpdates

