language: objective-c
cache: cocoapods 
podfile: QCloudCOSXMLDemo/Podfile 
xcode_workspace: QCloudCOSXMLDemo/QCloudCOSXMLDemo.xcworkspace
xcode_scheme: QCloudCOSXMLDemo/QCloudCOSXMLDemoTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

