language: objective-c
xcode_workspace: QCloudCOSXMLDemo/QCloudCOSXMLDemo.xcworkspace
xcode_scheme: QCloudCOSXMLDemo/QCloudCOSXMLDemoTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
script: xcodebuild build-for-testing   -workspace QCloudCOSXMLDemo.xcworkspace -scheme  QCloudCOSXMLDemoTests  -allowProvisioningUpdates

