language: objective-c
cache: cocoapods 
podfile: Podfile 
xcode_workspace: QCloudCOSXMLDemo.xcworkspace
xcode_scheme: QCloudCOSXMLDemoTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
before_script:
  # Create and start emulator
  - cd QCloudCOSXMLDemo

